services:
  # XA Web UI
  xawebui:
    image: widyansyahh/academy_fe:dev
    hostname: xawebui
    container_name: xawebui
    # depends_on:
    #   - xawebapi
    networks:
      - xmu_network
    restart: always

networks:
  xmu_network:
    external: true